apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moltbook

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: moltbook
  component: frontend

images:
  - name: quay.io/YOUR_ORG/moltbook-frontend
    newTag: latest
